#!/usr/bin/env python3
"""Generate devcontainer named-volume overlays for plugin frontend node_modules.

Run this from the repository root after adding a new plugin with a frontend
package.json. It updates the generated overlay files so that
`docker-compose.yml` (which includes the overlay) and the Dockerfile pick up
the new `frontend/node_modules` mount point automatically.
"""
from __future__ import annotations

import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def discover_frontends(plugins_dir: Path) -> list[Path]:
    return sorted(plugins_dir.glob("*/frontend/package.json"))


def write_overlay(devcontainer_dir: Path, frontends: list[Path]) -> None:
    lines: list[str] = []
    lines.append(
        "# Generated by .devcontainer/generate-frontend-volumes.py — do not edit manually."
    )
    lines.append(
        "# Run the generator to update when a new plugin frontend is added."
    )
    lines.append("services:")
    lines.append("  toolkit:")
    lines.append("    volumes:")

    for package_json in frontends:
        plugin_dir = package_json.parents[1].name
        volume_name = f"{plugin_dir}-frontend-node-modules"
        container_path = f"/workspace/plugins/{plugin_dir}/frontend/node_modules"
        lines.append(f"      - {volume_name}:{container_path}")

    lines.append("")
    lines.append("volumes:")
    for package_json in frontends:
        plugin_dir = package_json.parents[1].name
        volume_name = f"{plugin_dir}-frontend-node-modules"
        lines.append(f"  {volume_name}:")

    (devcontainer_dir / "docker-compose.frontend-volumes.yml").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def write_mounts_list(devcontainer_dir: Path, frontends: list[Path]) -> None:
    paths: list[str] = []
    for package_json in frontends:
        plugin_dir = package_json.parents[1].name
        container_path = f"/workspace/plugins/{plugin_dir}/frontend/node_modules"
        paths.append(container_path)

    (devcontainer_dir / "frontend-node-modules-mounts.txt").write_text(
        "\n".join(paths) + "\n", encoding="utf-8"
    )


def main() -> int:
    root = repo_root()
    plugins_dir = root / "plugins"
    devcontainer_dir = root / ".devcontainer"

    frontends = discover_frontends(plugins_dir)
    if not frontends:
        print(
            "No plugin frontends found; generated files will be empty.",
            file=sys.stderr,
        )

    write_overlay(devcontainer_dir, frontends)
    write_mounts_list(devcontainer_dir, frontends)

    print(
        f"Generated named-volume overlays for {len(frontends)} plugin frontend(s)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
